### ISSUE TITLE
메뉴를 저장하는 기준 날짜 변경

### ISSUE THREAD

**Issue by Rybczinski0726** [floating-cloud01/floatingcloud#13]
AS-IS : 당일 메뉴만 저장
TO-BE : 메뉴가 언제까지 올라오는지 확인해 넉넉하게 지정
> API 확인해본 바로는 금주 토요일 메뉴까지 올라오는 듯 합니다.

**Comment by Rybczinski0726** [comment]
지금 확인해보니 다음주 메뉴가 모두 올라와 있네요

**Comment by skyskai** [comment]
오늘 기준으로 +N일 형태로 데이터가 있을듯한데..
금요일에는 다음주 메뉴가 올라오고 이런 형태..
